# filename: codebase/step_3.py
import sys
import os
sys.path.insert(0, os.path.abspath("codebase"))
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

if __name__ == '__main__':
    pd.set_option('display.max_columns', None)
    pd.set_option('display.max_rows', None)
    pd.set_option('display.width', 1000)
    file_path = '/home/node/work/projects/materials_project_v3/perovskite_data.csv'
    df = pd.read_csv(file_path)
    cols_to_drop = [col for col in df.columns if col.endswith('.1')]
    df = df.drop(columns=cols_to_drop)
    plt.rcParams['text.usetex'] = False
    fig, axes = plt.subplots(4, 3, figsize=(24, 24))
    axes = axes.flatten()
    order = df['crystal_system'].value_counts().index.tolist()
    sns.countplot(data=df, x='crystal_system', order=order, ax=axes[0], hue='crystal_system', palette='viridis', legend=False)
    axes[0].set_title('Crystal System Frequency')
    axes[0].set_xlabel('Crystal System')
    axes[0].set_ylabel('Count')
    axes[0].tick_params(axis='x', rotation=45)
    sns.histplot(data=df, x='formation_energy_per_atom', bins=50, ax=axes[1], color='skyblue')
    axes[1].set_title('Formation Energy per Atom')
    axes[1].set_xlabel('Formation Energy (eV/atom)')
    axes[1].set_ylabel('Frequency')
    sns.histplot(data=df, x='band_gap', bins=50, ax=axes[2], color='lightgreen')
    axes[2].set_title('Band Gap')
    axes[2].set_xlabel('Band Gap (eV)')
    axes[2].set_ylabel('Frequency')
    sns.histplot(data=df, x='volume', bins=50, ax=axes[3], color='salmon', log_scale=(True, False))
    axes[3].set_title('Volume (Log Scale)')
    axes[3].set_xlabel('Volume (Å³)')
    axes[3].set_ylabel('Frequency')
    sns.histplot(data=df, x='tau', bins=50, ax=axes[4], color='orchid')
    axes[4].set_title('Goldschmidt Tolerance Factor (tau)')
    axes[4].set_xlabel('tau')
    axes[4].set_ylabel('Frequency')
    sns.histplot(data=df, x='K_VRH', bins=50, binrange=(0, 300), ax=axes[5], color='gold')
    axes[5].set_title('Bulk Modulus (K_VRH) [0-300 GPa]')
    axes[5].set_xlabel('K_VRH (GPa)')
    axes[5].set_ylabel('Frequency')
    sns.histplot(data=df, x='G_VRH', bins=50, binrange=(-20, 200), ax=axes[6], color='orange')
    axes[6].set_title('Shear Modulus (G_VRH) [-20-200 GPa]')
    axes[6].set_xlabel('G_VRH (GPa)')
    axes[6].set_ylabel('Frequency')
    sns.histplot(data=df, x='poisson_ratio', bins=50, ax=axes[7], color='teal')
    axes[7].set_title('Poisson Ratio')
    axes[7].set_xlabel('Poisson Ratio')
    axes[7].set_ylabel('Frequency')
    sns.histplot(data=df, x='elastic_anisotropy', bins=50, ax=axes[8], color='purple', log_scale=(True, False))
    axes[8].set_title('Elastic Anisotropy (Log Scale)')
    axes[8].set_xlabel('Elastic Anisotropy')
    axes[8].set_ylabel('Frequency')
    sns.scatterplot(data=df, x='tau', y='energy_above_hull', hue='crystal_system', ax=axes[9], palette='Set1', alpha=0.7)
    axes[9].set_title('tau vs. Energy Above Hull')
    axes[9].set_xlabel('Goldschmidt Tolerance Factor (tau)')
    axes[9].set_ylabel('Energy Above Hull (eV/atom)')
    axes[9].legend_.remove()
    corr_cols = ['volume', 'density', 'formation_energy_per_atom', 'energy_above_hull', 'tau', 'mu', 'A_en', 'B_en', 'A_radius', 'B_radius', 'en_diff', 'radius_ratio', 'band_gap', 'K_VRH', 'G_VRH']
    corr_matrix = df[corr_cols].corr()
    sns.heatmap(corr_matrix, ax=axes[10], cmap='coolwarm', annot=True, fmt=".2f", annot_kws={"size": 8}, cbar_kws={'shrink': 0.8})
    axes[10].set_title('Correlation Matrix')
    axes[10].set_xticklabels(axes[10].get_xticklabels(), rotation=45, ha='right')
    axes[10].tick_params(axis='y', rotation=0)
    axes[11].axis('off')
    handles, labels = axes[9].get_legend_handles_labels()
    axes[11].legend(handles, labels, title='Crystal System', loc='center', fontsize=14, title_fontsize=16)
    fig.suptitle('ABO3 Perovskite Dataset - Property Distributions', fontsize=24)
    plt.tight_layout(rect=[0, 0, 1, 0.98])
    timestamp = str(int(datetime.now().timestamp()))
    plot_filename = "property_distributions_" + timestamp + ".png"
    plot_filepath = os.path.join("data", plot_filename)
    plt.savefig(plot_filepath, dpi=300, bbox_inches='tight')
    print("Multi-panel figure saved to " + plot_filepath)
    print("\n--- Quantitative Information for Visualized Distributions ---")
    print("Crystal System Frequencies:")
    print(df['crystal_system'].value_counts().to_string())
    print("\nFormation Energy per Atom (eV/atom):")
    print(df['formation_energy_per_atom'].describe().to_string())
    print("\nBand Gap (eV):")
    print(df['band_gap'].describe().to_string())
    print("\nVolume (Å³):")
    print(df['volume'].describe().to_string())
    print("\nGoldschmidt Tolerance Factor (tau):")
    print(df['tau'].describe().to_string())
    print("\nElastic Properties (215 available entries):")
    elastic_cols = ['K_VRH', 'G_VRH', 'poisson_ratio', 'elastic_anisotropy']
    print(df[elastic_cols].describe(percentiles=[0.01, 0.25, 0.5, 0.75, 0.99]).to_string())
    print("\nOutliers excluded from K_VRH histogram (K_VRH > 300 GPa):")
    print(df[df['K_VRH'] > 300][['material_id', 'formula', 'K_VRH']].to_string())
    print("\nOutliers excluded from G_VRH histogram (G_VRH > 200 GPa or G_VRH < -20 GPa):")
    print(df[(df['G_VRH'] > 200) | (df['G_VRH'] < -20)][['material_id', 'formula', 'G_VRH']].to_string())